# + -------------------------------------------------------------------------------- + #
# | MESSAGE, ERRORMESSAGE SETTINGS ( 메시지 설정 )
# | 유저에게 출력되지 않을 메세지는 해당 라인을 지우시거나
# | 해당 라인의 제일 앞에 '#' 을 붙여 주석으로 처리하시면 됩니다.
# + -------------------------------------------------------------------------------- + #

messages:
  # (메시지 앞에 붙는) 접두사
  prefix: " &6밴아이템 | "

  # '/밴아이템 확인 [플레이어]' 명령어 사용 성공 시
  checkComplete: "&a인벤토리 검사를 완료하였습니다!"

  # 리로드 완료 시
  reloadComplete: "&a콘피그를 리로드하였습니다."

errorMessages:
  # 잘못된 명령어 입력 시
  wrongCommand: "&c잘못된 명령어입니다. 위키에서 명령어를 확인해주세요!"

  # 콘솔 사용 불가 명령어를 콘솔에서 사용 시
  noConsole: "&c해당 명령어는 콘솔에서 사용할 수 없습니다."

  # 권한이 부족할 시
  permissionDenied: "&c권한이 부족합니다!"

  # 존재하지 않는 플레이어를 명령어에 사용했을 시
  noPlayer: "&c존재하지 않는 플레이어입니다!"

  # 존재하지 않는 월드의 설정을 변경하려 시도 했을 때
  noWorld: "&c존재하지 않는 월드 이름입니다!"

  # 밴 아이템을 획독 혹은 사용하려 했을 때
  itemBanned: "&c해당 아이템은 밴 아이템 입니다!"